--
-- TOC entry 216 (class 1259 OID 18343)
-- Name: account; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account
(
    account_id       bigint                 NOT NULL,
    create_date_time timestamp(6) with time zone,
    is_delete        boolean,
    update_date_time timestamp(6) with time zone,
    address          character varying(255),
    date_of_birth    date,
    email            character varying(255) NOT NULL,
    first_name       character varying(255),
    last_name        character varying(255),
    password         character varying(255),
    phone            character varying(255),
    user_name        character varying(255) NOT NULL
);


ALTER TABLE public.account
    OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 18342)
-- Name: account_account_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.account
    ALTER COLUMN account_id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.account_account_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );


--
-- TOC entry 217 (class 1259 OID 18350)
-- Name: account_role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account_role
(
    account_id bigint NOT NULL,
    role_id    bigint NOT NULL
);


ALTER TABLE public.account_role
    OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 18356)
-- Name: refresh_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.refresh_token
(
    refresh_token_id bigint                      NOT NULL,
    create_date_time timestamp(6) with time zone,
    is_delete        boolean,
    update_date_time timestamp(6) with time zone,
    expiry_date      timestamp(6) with time zone NOT NULL,
    token            character varying(255)      NOT NULL,
    account_id       bigint
);


ALTER TABLE public.refresh_token
    OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 18355)
-- Name: refresh_token_refresh_token_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.refresh_token
    ALTER COLUMN refresh_token_id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.refresh_token_refresh_token_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );


--
-- TOC entry 221 (class 1259 OID 18362)
-- Name: role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role
(
    role_id          bigint NOT NULL,
    create_date_time timestamp(6) with time zone,
    is_delete        boolean,
    update_date_time timestamp(6) with time zone,
    role_name        character varying(255),
    CONSTRAINT role_role_name_check CHECK (((role_name)::text = ANY
                                            ((ARRAY ['MANAGER'::character varying, 'ADMIN'::character varying, 'USER'::character varying])::text[])))
);


ALTER TABLE public.role
    OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 18361)
-- Name: role_role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.role
    ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.role_role_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );

--
-- TOC entry 4819 (class 0 OID 18362)
-- Dependencies: 221
-- Data for Name: role; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.role (is_delete, create_date_time, update_date_time, role_name)
VALUES (false, '2024-08-02 00:00:00+00', '2024-08-02 00:00:00+00', 'MANAGER'),
       (false, '2024-08-02 00:00:00+00', '2024-08-02 00:00:00+00', 'ADMIN'),
       (false, '2024-08-02 00:00:00+00', '2024-08-02 00:00:00+00', 'USER');

--
-- TOC entry 4650 (class 2606 OID 18349)
-- Name: account account_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (account_id);


--
-- TOC entry 4656 (class 2606 OID 18354)
-- Name: account_role account_role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_role
    ADD CONSTRAINT account_role_pkey PRIMARY KEY (account_id, role_id);


--
-- TOC entry 4658 (class 2606 OID 18360)
-- Name: refresh_token refresh_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (refresh_token_id);


--
-- TOC entry 4664 (class 2606 OID 18367)
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (role_id);


--
-- TOC entry 4660 (class 2606 OID 18375)
-- Name: refresh_token uk1gnoedr4u8s5p7ccdkftq38bh; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT uk1gnoedr4u8s5p7ccdkftq38bh UNIQUE (account_id);


--
-- TOC entry 4652 (class 2606 OID 18371)
-- Name: account ukf6xpj7h12wr185bqhfi1hqlbr; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT ukf6xpj7h12wr185bqhfi1hqlbr UNIQUE (user_name);


--
-- TOC entry 4666 (class 2606 OID 18377)
-- Name: role ukiubw515ff0ugtm28p8g3myt0h; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT ukiubw515ff0ugtm28p8g3myt0h UNIQUE (role_name);


--
-- TOC entry 4654 (class 2606 OID 18369)
-- Name: account ukq0uja26qgu1atulenwup9rxyr; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT ukq0uja26qgu1atulenwup9rxyr UNIQUE (email);


--
-- TOC entry 4662 (class 2606 OID 18373)
-- Name: refresh_token ukr4k4edos30bx9neoq81mdvwph; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT ukr4k4edos30bx9neoq81mdvwph UNIQUE (token);


--
-- TOC entry 4667 (class 2606 OID 18383)
-- Name: account_role fk1f8y4iy71kb1arff79s71j0dh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_role
    ADD CONSTRAINT fk1f8y4iy71kb1arff79s71j0dh FOREIGN KEY (account_id) REFERENCES public.account (account_id);


--
-- TOC entry 4669 (class 2606 OID 18388)
-- Name: refresh_token fkiox3wo9jixvp9boxfheq7l99w; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT fkiox3wo9jixvp9boxfheq7l99w FOREIGN KEY (account_id) REFERENCES public.account (account_id);


--
-- TOC entry 4668 (class 2606 OID 18378)
-- Name: account_role fkrs2s3m3039h0xt8d5yhwbuyam; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_role
    ADD CONSTRAINT fkrs2s3m3039h0xt8d5yhwbuyam FOREIGN KEY (role_id) REFERENCES public.role (role_id);


-- Completed on 2024-08-03 21:29:39


