--
-- TOC entry 216 (class 1259 OID 18343)
-- Name: account; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account
(
    account_id       bigint                 NOT NULL,
    create_date_time timestamp(6) with time zone,
    is_delete        boolean,
    update_date_time timestamp(6) with time zone,
    address          character varying(255),
    date_of_birth    date,
    email            character varying(255) NOT NULL,
    first_name       character varying(255),
    last_name        character varying(255),
    password         character varying(255),
    phone            character varying(255),
    user_name        character varying(255) NOT NULL
);


ALTER TABLE public.account
    OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 18342)
-- Name: account_account_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.account
    ALTER COLUMN account_id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.account_account_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );


--
-- TOC entry 217 (class 1259 OID 18350)
-- Name: account_role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account_role
(
    account_id bigint NOT NULL,
    role_id    bigint NOT NULL
);


ALTER TABLE public.account_role
    OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 18356)
-- Name: refresh_token; Type: TABLE; Schema: public; Owner: postgres
--

--
-- TOC entry 220 (class 1259 OID 19611)
-- Name: permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.permission
(
    is_delete        boolean,
    create_date_time timestamp(6) with time zone,
    permission_id    bigint NOT NULL,
    update_date_time timestamp(6) with time zone,
    permission_name  character varying(255),
    CONSTRAINT permission_permission_name_check CHECK (((permission_name)::text = ANY
                                                        ((ARRAY ['USER_CREATE'::character varying, 'USER_ACCESS'::character varying, 'USER_DELETE'::character varying, 'USER_EDIT'::character varying, 'USER_SHOW'::character varying])::text[])))
);


ALTER TABLE public.permission
    OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 19610)
-- Name: permission_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.permission
    ALTER COLUMN permission_id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.permission_permission_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );

CREATE TABLE public.refresh_token
(
    refresh_token_id bigint                      NOT NULL,
    create_date_time timestamp(6) with time zone,
    is_delete        boolean,
    update_date_time timestamp(6) with time zone,
    expiry_date      timestamp(6) with time zone NOT NULL,
    token            character varying(255)      NOT NULL,
    account_id       bigint
);


ALTER TABLE public.refresh_token
    OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 18355)
-- Name: refresh_token_refresh_token_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.refresh_token
    ALTER COLUMN refresh_token_id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.refresh_token_refresh_token_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );


--
-- TOC entry 221 (class 1259 OID 18362)
-- Name: role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role
(
    role_id          bigint NOT NULL,
    create_date_time timestamp(6) with time zone,
    is_delete        boolean,
    update_date_time timestamp(6) with time zone,
    role_name        character varying(255),
    CONSTRAINT role_role_name_check CHECK (((role_name)::text = ANY
                                            ((ARRAY ['MANAGER'::character varying, 'ADMIN'::character varying, 'USER'::character varying])::text[])))
);


ALTER TABLE public.role
    OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 18361)
-- Name: role_role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.role
    ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.role_role_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );

--
-- TOC entry 225 (class 1259 OID 19638)
-- Name: role_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role_permission
(
    permission_id bigint NOT NULL,
    role_id       bigint NOT NULL
);


ALTER TABLE public.role_permission
    OWNER TO postgres;

--
-- TOC entry 4819 (class 0 OID 18362)
-- Dependencies: 221
-- Data for Name: role; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.permission (is_delete, create_date_time, permission_id, update_date_time, permission_name)
VALUES (false, '2024-08-05 17:14:24.151181+07', 1, '2024-08-05 17:14:24.15218+07', 'USER_CREATE'),
       (false, '2024-08-05 17:14:24.206268+07', 2, '2024-08-05 17:14:24.206268+07', 'USER_ACCESS'),
       (false, '2024-08-05 17:14:24.210223+07', 3, '2024-08-05 17:14:24.210223+07', 'USER_DELETE'),
       (false, '2024-08-05 17:14:24.21322+07', 4, '2024-08-05 17:14:24.21322+07', 'USER_EDIT'),
       (false, '2024-08-05 17:14:24.215222+07', 5, '2024-08-05 17:14:24.215222+07', 'USER_SHOW');


INSERT INTO public.role (is_delete, create_date_time, role_id, update_date_time, role_name)
VALUES (false, '2024-08-05 17:14:24.346061+07', 1, '2024-08-05 17:14:24.346061+07', 'MANAGER'),
       (false, '2024-08-05 17:14:24.372061+07', 2, '2024-08-05 17:14:24.372061+07', 'ADMIN'),
       (false, '2024-08-05 17:14:24.380061+07', 3, '2024-08-05 17:14:24.380061+07', 'USER');

INSERT INTO public.role_permission (permission_id, role_id)
VALUES (3, 1),
       (1, 1),
       (4, 1),
       (2, 1),
       (5, 1),
       (5, 2),
       (4, 2),
       (1, 2),
       (2, 2),
       (2, 3),
       (4, 3);


--
-- TOC entry 4668 (class 2606 OID 19602)
-- Name: account account_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_email_key UNIQUE (email);


--
-- TOC entry 4670 (class 2606 OID 19600)
-- Name: account account_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (account_id);


--
-- TOC entry 4674 (class 2606 OID 19609)
-- Name: account_role account_role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_role
    ADD CONSTRAINT account_role_pkey PRIMARY KEY (account_id, role_id);


--
-- TOC entry 4672 (class 2606 OID 19604)
-- Name: account account_user_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_user_name_key UNIQUE (user_name);


--
-- TOC entry 4676 (class 2606 OID 19618)
-- Name: permission permission_permission_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permission
    ADD CONSTRAINT permission_permission_name_key UNIQUE (permission_name);


--
-- TOC entry 4678 (class 2606 OID 19616)
-- Name: permission permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permission
    ADD CONSTRAINT permission_pkey PRIMARY KEY (permission_id);


--
-- TOC entry 4680 (class 2606 OID 19626)
-- Name: refresh_token refresh_token_account_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_account_id_key UNIQUE (account_id);


--
-- TOC entry 4682 (class 2606 OID 19624)
-- Name: refresh_token refresh_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (refresh_token_id);


--
-- TOC entry 4684 (class 2606 OID 19628)
-- Name: refresh_token refresh_token_token_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_token_key UNIQUE (token);


--
-- TOC entry 4690 (class 2606 OID 19642)
-- Name: role_permission role_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permission
    ADD CONSTRAINT role_permission_pkey PRIMARY KEY (permission_id, role_id);


--
-- TOC entry 4686 (class 2606 OID 19635)
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (role_id);


--
-- TOC entry 4688 (class 2606 OID 19637)
-- Name: role role_role_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_role_name_key UNIQUE (role_name);



--
-- TOC entry 4691 (class 2606 OID 19648)
-- Name: account_role fk1f8y4iy71kb1arff79s71j0dh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_role
    ADD CONSTRAINT fk1f8y4iy71kb1arff79s71j0dh FOREIGN KEY (account_id) REFERENCES public.account (account_id);


--
-- TOC entry 4694 (class 2606 OID 19663)
-- Name: role_permission fka6jx8n8xkesmjmv6jqug6bg68; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permission
    ADD CONSTRAINT fka6jx8n8xkesmjmv6jqug6bg68 FOREIGN KEY (role_id) REFERENCES public.role (role_id);


--
-- TOC entry 4695 (class 2606 OID 19658)
-- Name: role_permission fkf8yllw1ecvwqy3ehyxawqa1qp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permission
    ADD CONSTRAINT fkf8yllw1ecvwqy3ehyxawqa1qp FOREIGN KEY (permission_id) REFERENCES public.permission (permission_id);


--
-- TOC entry 4693 (class 2606 OID 19653)
-- Name: refresh_token fkiox3wo9jixvp9boxfheq7l99w; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT fkiox3wo9jixvp9boxfheq7l99w FOREIGN KEY (account_id) REFERENCES public.account (account_id);


--
-- TOC entry 4692 (class 2606 OID 19643)
-- Name: account_role fkrs2s3m3039h0xt8d5yhwbuyam; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_role
    ADD CONSTRAINT fkrs2s3m3039h0xt8d5yhwbuyam FOREIGN KEY (role_id) REFERENCES public.role (role_id);


-- Completed on 2024-08-05 21:20:33

--
-- PostgreSQL database dump complete
--